# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 16:00
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompoundObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geometry', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public', models.BooleanField()),
                ('name', models.CharField(max_length=20)),
                ('descr', models.TextField()),
                ('logo', models.ImageField(upload_to='img/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GeomType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='LineObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geometry', django.contrib.gis.db.models.fields.LineStringField(srid=3857)),
            ],
        ),
        migrations.CreateModel(
            name='ModelObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bbox', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=3857)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_objects', to='app.Dataset')),
                ('geom_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_objects', to='app.GeomType')),
            ],
        ),
        migrations.CreateModel(
            name='ObjectType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PointObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geometry', django.contrib.gis.db.models.fields.PointField(srid=3857)),
                ('model_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_objects', to='app.ModelObject')),
            ],
        ),
        migrations.CreateModel(
            name='PolygonObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geometry', django.contrib.gis.db.models.fields.PolygonField(srid=3857)),
                ('model_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polygon_objects', to='app.ModelObject')),
            ],
        ),
        migrations.CreateModel(
            name='Prop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_series', models.BooleanField()),
                ('model_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='app.ModelObject')),
                ('obs_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='observed_properties', to='app.PointObject')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_type', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('value_num', models.FloatField(blank=True, null=True)),
                ('value_cat', models.CharField(blank=True, max_length=20, null=True)),
                ('value_ras', django.contrib.gis.db.models.fields.RasterField(blank=True, null=True, srid=3857)),
                ('prop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='app.Prop')),
            ],
        ),
        migrations.CreateModel(
            name='ValueSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamps', django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(), blank=True, null=True, size=None)),
                ('value_num', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None)),
                ('value_cat', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, null=True, size=None)),
                ('value_ras', django.contrib.gis.db.models.fields.RasterField(blank=True, null=True, srid=3857)),
                ('prop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values_series', to='app.Prop')),
            ],
        ),
        migrations.AddField(
            model_name='prop',
            name='property_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='app.PropertyType'),
        ),
        migrations.AddField(
            model_name='modelobject',
            name='object_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_objects', to='app.ObjectType'),
        ),
        migrations.AddField(
            model_name='lineobject',
            name='model_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_objects', to='app.ModelObject'),
        ),
        migrations.AddField(
            model_name='compoundobject',
            name='model_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compound_objects', to='app.ModelObject'),
        ),
    ]
