# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 13:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20161119_1407'),
    ]

    operations = [
        migrations.RenameField(
            model_name='valuetype',
            old_name='geom_type',
            new_name='value_type',
        ),
    ]
