# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 17:32
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20161119_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='TSRaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestart', models.DateTimeField(null=True)),
                ('interval', models.DurationField(null=True)),
                ('value', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.gis.db.models.fields.RasterField(srid=3857), null=True, size=None)),
                ('prop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ts_raster', to='app.Prop')),
            ],
        ),
    ]
