# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_tsraster'),
    ]

    operations = [
        migrations.AddField(
            model_name='rasvalue',
            name='timestep',
            field=models.DateTimeField(null=True),
        ),
    ]
