# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 11:24
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rasvalue_timestep'),
    ]

    operations = [
        migrations.CreateModel(
            name='RasterSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestart', models.DateTimeField(null=True)),
                ('interval', models.DurationField(null=True)),
                ('value', django.contrib.gis.db.models.fields.RasterField(srid=3857)),
                ('prop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raster_series', to='app.Prop')),
            ],
        ),
        migrations.RemoveField(
            model_name='rasvalue',
            name='timestep',
        ),
    ]
