# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20161130_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rasterseries',
            name='interval',
        ),
        migrations.RemoveField(
            model_name='rasterseries',
            name='timestart',
        ),
        migrations.RemoveField(
            model_name='tsvalue',
            name='interval',
        ),
        migrations.RemoveField(
            model_name='tsvalue',
            name='timestart',
        ),
        migrations.AddField(
            model_name='prop',
            name='interval',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prop',
            name='num_vals',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='prop',
            name='timestart',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
