# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20161206_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelobject',
            name='name',
            field=models.TextField(default='Noname'),
        ),
        migrations.AddField(
            model_name='prop',
            name='name',
            field=models.TextField(default='Noname'),
        ),
    ]
