# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-16 15:33
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20161206_1032'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValueSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(null=True), null=True, size=None)),
                ('prop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='value_series', to='app.Prop')),
            ],
        ),
        migrations.RemoveField(
            model_name='tsraster',
            name='prop',
        ),
        migrations.RemoveField(
            model_name='tsvalue',
            name='prop',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='logo',
        ),
        migrations.AddField(
            model_name='dataset',
            name='bbox',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=3857),
        ),
        migrations.DeleteModel(
            name='TSRaster',
        ),
        migrations.DeleteModel(
            name='TSValue',
        ),
    ]
