# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-16 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20161216_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geomtype',
            name='geom_type',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='objecttype',
            name='object_type',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='propertytype',
            name='property_type',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='valuetype',
            name='value_type',
            field=models.TextField(),
        ),
    ]
