# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-18 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_dataset_tile_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='tile_url',
            field=models.TextField(default='https://a.tile.openstreetmap.org/0/0/0.png'),
        ),
    ]
