version: '2'  
services:  
  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "8888:8000"
    volumes:
      - ./src:/src
      - ./config/nginx:/etc/nginx/conf.d
      - /static:/static
      - /media:/media
    depends_on:
      - web
  web:
    build: .
    container_name: django
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py collectstatic --noinput && gunicorn explorer.wsgi -b 0.0.0.0:8000"
    depends_on:
      - db
    volumes:
      - ./src:/src
      - /static:/static
      - /media:/media
    expose:
      - "8000"

  db:
    image: mdillon/postgis
    container_name: postgres
    expose:
      - "5432"